package pro.belbix.ethparser.codegen.abi;

public class Bsc1Inch {
  public static final String ABI = ""
      + "[\n"
      + "\t{\n"
      + "\t\t\"inputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"internalType\": \"address\",\n"
      + "\t\t\t\t\"name\": \"_storage\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t},\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"internalType\": \"address\",\n"
      + "\t\t\t\t\"name\": \"_vault\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"stateMutability\": \"nonpayable\",\n"
      + "\t\t\"type\": \"constructor\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"anonymous\": false,\n"
      + "\t\t\"inputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"indexed\": false,\n"
      + "\t\t\t\t\"internalType\": \"address\",\n"
      + "\t\t\t\t\"name\": \"token\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t},\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"indexed\": false,\n"
      + "\t\t\t\t\"internalType\": \"uint256\",\n"
      + "\t\t\t\t\"name\": \"amount\",\n"
      + "\t\t\t\t\"type\": \"uint256\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"name\": \"Liquidating\",\n"
      + "\t\t\"type\": \"event\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"anonymous\": false,\n"
      + "\t\t\"inputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"indexed\": false,\n"
      + "\t\t\t\t\"internalType\": \"uint256\",\n"
      + "\t\t\t\t\"name\": \"profitAmount\",\n"
      + "\t\t\t\t\"type\": \"uint256\"\n"
      + "\t\t\t},\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"indexed\": false,\n"
      + "\t\t\t\t\"internalType\": \"uint256\",\n"
      + "\t\t\t\t\"name\": \"feeAmount\",\n"
      + "\t\t\t\t\"type\": \"uint256\"\n"
      + "\t\t\t},\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"indexed\": false,\n"
      + "\t\t\t\t\"internalType\": \"uint256\",\n"
      + "\t\t\t\t\"name\": \"timestamp\",\n"
      + "\t\t\t\t\"type\": \"uint256\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"name\": \"ProfitLogInReward\",\n"
      + "\t\t\"type\": \"event\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"anonymous\": false,\n"
      + "\t\t\"inputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"indexed\": false,\n"
      + "\t\t\t\t\"internalType\": \"address\",\n"
      + "\t\t\t\t\"name\": \"token\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"name\": \"ProfitsNotCollected\",\n"
      + "\t\t\"type\": \"event\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"inputs\": [],\n"
      + "\t\t\"name\": \"_wbnb\",\n"
      + "\t\t\"outputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"internalType\": \"address\",\n"
      + "\t\t\t\t\"name\": \"\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"stateMutability\": \"view\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"inputs\": [],\n"
      + "\t\t\"name\": \"controller\",\n"
      + "\t\t\"outputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"internalType\": \"address\",\n"
      + "\t\t\t\t\"name\": \"\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"stateMutability\": \"view\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"inputs\": [],\n"
      + "\t\t\"name\": \"depositArbCheck\",\n"
      + "\t\t\"outputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"internalType\": \"bool\",\n"
      + "\t\t\t\t\"name\": \"\",\n"
      + "\t\t\t\t\"type\": \"bool\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"stateMutability\": \"view\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"inputs\": [],\n"
      + "\t\t\"name\": \"doHardWork\",\n"
      + "\t\t\"outputs\": [],\n"
      + "\t\t\"stateMutability\": \"nonpayable\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"inputs\": [],\n"
      + "\t\t\"name\": \"governance\",\n"
      + "\t\t\"outputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"internalType\": \"address\",\n"
      + "\t\t\t\t\"name\": \"\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"stateMutability\": \"view\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"inputs\": [],\n"
      + "\t\t\"name\": \"investAllUnderlying\",\n"
      + "\t\t\"outputs\": [],\n"
      + "\t\t\"stateMutability\": \"nonpayable\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"inputs\": [],\n"
      + "\t\t\"name\": \"investedUnderlyingBalance\",\n"
      + "\t\t\"outputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"internalType\": \"uint256\",\n"
      + "\t\t\t\t\"name\": \"\",\n"
      + "\t\t\t\t\"type\": \"uint256\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"stateMutability\": \"view\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"inputs\": [],\n"
      + "\t\t\"name\": \"oneInch\",\n"
      + "\t\t\"outputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"internalType\": \"address\",\n"
      + "\t\t\t\t\"name\": \"\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"stateMutability\": \"view\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"inputs\": [],\n"
      + "\t\t\"name\": \"oneInchBNBLP\",\n"
      + "\t\t\"outputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"internalType\": \"address\",\n"
      + "\t\t\t\t\"name\": \"\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"stateMutability\": \"view\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"inputs\": [],\n"
      + "\t\t\"name\": \"oneInchEthLP\",\n"
      + "\t\t\"outputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"internalType\": \"address\",\n"
      + "\t\t\t\t\"name\": \"\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"stateMutability\": \"view\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"inputs\": [],\n"
      + "\t\t\"name\": \"pancakeRouterV2\",\n"
      + "\t\t\"outputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"internalType\": \"address\",\n"
      + "\t\t\t\t\"name\": \"\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"stateMutability\": \"view\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"inputs\": [],\n"
      + "\t\t\"name\": \"pool\",\n"
      + "\t\t\"outputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"internalType\": \"address\",\n"
      + "\t\t\t\t\"name\": \"\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"stateMutability\": \"view\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"inputs\": [],\n"
      + "\t\t\"name\": \"profitSharingDenominator\",\n"
      + "\t\t\"outputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"internalType\": \"uint256\",\n"
      + "\t\t\t\t\"name\": \"\",\n"
      + "\t\t\t\t\"type\": \"uint256\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"stateMutability\": \"view\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"inputs\": [],\n"
      + "\t\t\"name\": \"profitSharingNumerator\",\n"
      + "\t\t\"outputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"internalType\": \"uint256\",\n"
      + "\t\t\t\t\"name\": \"\",\n"
      + "\t\t\t\t\"type\": \"uint256\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"stateMutability\": \"view\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"inputs\": [],\n"
      + "\t\t\"name\": \"renBTC\",\n"
      + "\t\t\"outputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"internalType\": \"address\",\n"
      + "\t\t\t\t\"name\": \"\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"stateMutability\": \"view\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"inputs\": [],\n"
      + "\t\t\"name\": \"rewardToken\",\n"
      + "\t\t\"outputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"internalType\": \"address\",\n"
      + "\t\t\t\t\"name\": \"\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"stateMutability\": \"view\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"inputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"internalType\": \"address\",\n"
      + "\t\t\t\t\"name\": \"recipient\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t},\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"internalType\": \"address\",\n"
      + "\t\t\t\t\"name\": \"token\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t},\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"internalType\": \"uint256\",\n"
      + "\t\t\t\t\"name\": \"amount\",\n"
      + "\t\t\t\t\"type\": \"uint256\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"name\": \"salvage\",\n"
      + "\t\t\"outputs\": [],\n"
      + "\t\t\"stateMutability\": \"nonpayable\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"inputs\": [],\n"
      + "\t\t\"name\": \"sell\",\n"
      + "\t\t\"outputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"internalType\": \"bool\",\n"
      + "\t\t\t\t\"name\": \"\",\n"
      + "\t\t\t\t\"type\": \"bool\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"stateMutability\": \"view\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"inputs\": [],\n"
      + "\t\t\"name\": \"sellFloorOneInch\",\n"
      + "\t\t\"outputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"internalType\": \"uint256\",\n"
      + "\t\t\t\t\"name\": \"\",\n"
      + "\t\t\t\t\"type\": \"uint256\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"stateMutability\": \"view\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"inputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"internalType\": \"bool\",\n"
      + "\t\t\t\t\"name\": \"s\",\n"
      + "\t\t\t\t\"type\": \"bool\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"name\": \"setSell\",\n"
      + "\t\t\"outputs\": [],\n"
      + "\t\t\"stateMutability\": \"nonpayable\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"inputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"internalType\": \"uint256\",\n"
      + "\t\t\t\t\"name\": \"_sellFloorOneInch\",\n"
      + "\t\t\t\t\"type\": \"uint256\"\n"
      + "\t\t\t},\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"internalType\": \"uint256\",\n"
      + "\t\t\t\t\"name\": \"_slippageNumerator\",\n"
      + "\t\t\t\t\"type\": \"uint256\"\n"
      + "\t\t\t},\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"internalType\": \"uint256\",\n"
      + "\t\t\t\t\"name\": \"_slippageDenominator\",\n"
      + "\t\t\t\t\"type\": \"uint256\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"name\": \"setSellFloorAndSlippages\",\n"
      + "\t\t\"outputs\": [],\n"
      + "\t\t\"stateMutability\": \"nonpayable\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"inputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"internalType\": \"address\",\n"
      + "\t\t\t\t\"name\": \"_store\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"name\": \"setStorage\",\n"
      + "\t\t\"outputs\": [],\n"
      + "\t\t\"stateMutability\": \"nonpayable\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"inputs\": [],\n"
      + "\t\t\"name\": \"store\",\n"
      + "\t\t\"outputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"internalType\": \"contract Storage\",\n"
      + "\t\t\t\t\"name\": \"\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"stateMutability\": \"view\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"inputs\": [],\n"
      + "\t\t\"name\": \"token1\",\n"
      + "\t\t\"outputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"internalType\": \"address\",\n"
      + "\t\t\t\t\"name\": \"\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"stateMutability\": \"view\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"inputs\": [],\n"
      + "\t\t\"name\": \"underlying\",\n"
      + "\t\t\"outputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"internalType\": \"address\",\n"
      + "\t\t\t\t\"name\": \"\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"stateMutability\": \"view\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"inputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"internalType\": \"address\",\n"
      + "\t\t\t\t\"name\": \"\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"name\": \"unsalvagableTokens\",\n"
      + "\t\t\"outputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"internalType\": \"bool\",\n"
      + "\t\t\t\t\"name\": \"\",\n"
      + "\t\t\t\t\"type\": \"bool\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"stateMutability\": \"view\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"inputs\": [],\n"
      + "\t\t\"name\": \"unused_is_1inch\",\n"
      + "\t\t\"outputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"internalType\": \"bool\",\n"
      + "\t\t\t\t\"name\": \"\",\n"
      + "\t\t\t\t\"type\": \"bool\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"stateMutability\": \"view\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"inputs\": [],\n"
      + "\t\t\"name\": \"vault\",\n"
      + "\t\t\"outputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"internalType\": \"address\",\n"
      + "\t\t\t\t\"name\": \"\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"stateMutability\": \"view\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"inputs\": [],\n"
      + "\t\t\"name\": \"withdrawAllToVault\",\n"
      + "\t\t\"outputs\": [],\n"
      + "\t\t\"stateMutability\": \"nonpayable\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"inputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"internalType\": \"uint256\",\n"
      + "\t\t\t\t\"name\": \"amountUnderlying\",\n"
      + "\t\t\t\t\"type\": \"uint256\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"name\": \"withdrawToVault\",\n"
      + "\t\t\"outputs\": [],\n"
      + "\t\t\"stateMutability\": \"nonpayable\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"stateMutability\": \"payable\",\n"
      + "\t\t\"type\": \"receive\"\n"
      + "\t}\n"
      + "]";
}
