package pro.belbix.ethparser.codegen.abi;

public class LinkAbi {

  public static final String ABI = ""
      + "[\n"
      + "\t{\n"
      + "\t\t\"constant\": true,\n"
      + "\t\t\"inputs\": [],\n"
      + "\t\t\"name\": \"name\",\n"
      + "\t\t\"outputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"name\": \"\",\n"
      + "\t\t\t\t\"type\": \"string\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"payable\": false,\n"
      + "\t\t\"stateMutability\": \"view\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"constant\": false,\n"
      + "\t\t\"inputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"name\": \"_spender\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t},\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"name\": \"_value\",\n"
      + "\t\t\t\t\"type\": \"uint256\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"name\": \"approve\",\n"
      + "\t\t\"outputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"name\": \"\",\n"
      + "\t\t\t\t\"type\": \"bool\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"payable\": false,\n"
      + "\t\t\"stateMutability\": \"nonpayable\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"constant\": true,\n"
      + "\t\t\"inputs\": [],\n"
      + "\t\t\"name\": \"totalSupply\",\n"
      + "\t\t\"outputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"name\": \"\",\n"
      + "\t\t\t\t\"type\": \"uint256\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"payable\": false,\n"
      + "\t\t\"stateMutability\": \"view\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"constant\": false,\n"
      + "\t\t\"inputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"name\": \"_from\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t},\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"name\": \"_to\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t},\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"name\": \"_value\",\n"
      + "\t\t\t\t\"type\": \"uint256\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"name\": \"transferFrom\",\n"
      + "\t\t\"outputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"name\": \"\",\n"
      + "\t\t\t\t\"type\": \"bool\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"payable\": false,\n"
      + "\t\t\"stateMutability\": \"nonpayable\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"constant\": true,\n"
      + "\t\t\"inputs\": [],\n"
      + "\t\t\"name\": \"decimals\",\n"
      + "\t\t\"outputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"name\": \"\",\n"
      + "\t\t\t\t\"type\": \"uint8\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"payable\": false,\n"
      + "\t\t\"stateMutability\": \"view\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"constant\": false,\n"
      + "\t\t\"inputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"name\": \"_to\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t},\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"name\": \"_value\",\n"
      + "\t\t\t\t\"type\": \"uint256\"\n"
      + "\t\t\t},\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"name\": \"_data\",\n"
      + "\t\t\t\t\"type\": \"bytes\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"name\": \"transferAndCall\",\n"
      + "\t\t\"outputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"name\": \"success\",\n"
      + "\t\t\t\t\"type\": \"bool\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"payable\": false,\n"
      + "\t\t\"stateMutability\": \"nonpayable\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"constant\": false,\n"
      + "\t\t\"inputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"name\": \"_spender\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t},\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"name\": \"_subtractedValue\",\n"
      + "\t\t\t\t\"type\": \"uint256\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"name\": \"decreaseApproval\",\n"
      + "\t\t\"outputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"name\": \"success\",\n"
      + "\t\t\t\t\"type\": \"bool\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"payable\": false,\n"
      + "\t\t\"stateMutability\": \"nonpayable\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"constant\": true,\n"
      + "\t\t\"inputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"name\": \"_owner\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"name\": \"balanceOf\",\n"
      + "\t\t\"outputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"name\": \"balance\",\n"
      + "\t\t\t\t\"type\": \"uint256\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"payable\": false,\n"
      + "\t\t\"stateMutability\": \"view\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"constant\": true,\n"
      + "\t\t\"inputs\": [],\n"
      + "\t\t\"name\": \"symbol\",\n"
      + "\t\t\"outputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"name\": \"\",\n"
      + "\t\t\t\t\"type\": \"string\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"payable\": false,\n"
      + "\t\t\"stateMutability\": \"view\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"constant\": false,\n"
      + "\t\t\"inputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"name\": \"_to\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t},\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"name\": \"_value\",\n"
      + "\t\t\t\t\"type\": \"uint256\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"name\": \"transfer\",\n"
      + "\t\t\"outputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"name\": \"success\",\n"
      + "\t\t\t\t\"type\": \"bool\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"payable\": false,\n"
      + "\t\t\"stateMutability\": \"nonpayable\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"constant\": false,\n"
      + "\t\t\"inputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"name\": \"_spender\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t},\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"name\": \"_addedValue\",\n"
      + "\t\t\t\t\"type\": \"uint256\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"name\": \"increaseApproval\",\n"
      + "\t\t\"outputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"name\": \"success\",\n"
      + "\t\t\t\t\"type\": \"bool\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"payable\": false,\n"
      + "\t\t\"stateMutability\": \"nonpayable\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"constant\": true,\n"
      + "\t\t\"inputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"name\": \"_owner\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t},\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"name\": \"_spender\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"name\": \"allowance\",\n"
      + "\t\t\"outputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"name\": \"remaining\",\n"
      + "\t\t\t\t\"type\": \"uint256\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"payable\": false,\n"
      + "\t\t\"stateMutability\": \"view\",\n"
      + "\t\t\"type\": \"function\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"inputs\": [],\n"
      + "\t\t\"payable\": false,\n"
      + "\t\t\"stateMutability\": \"nonpayable\",\n"
      + "\t\t\"type\": \"constructor\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"anonymous\": false,\n"
      + "\t\t\"inputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"indexed\": true,\n"
      + "\t\t\t\t\"name\": \"from\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t},\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"indexed\": true,\n"
      + "\t\t\t\t\"name\": \"to\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t},\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"indexed\": false,\n"
      + "\t\t\t\t\"name\": \"value\",\n"
      + "\t\t\t\t\"type\": \"uint256\"\n"
      + "\t\t\t},\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"indexed\": false,\n"
      + "\t\t\t\t\"name\": \"data\",\n"
      + "\t\t\t\t\"type\": \"bytes\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"name\": \"Transfer\",\n"
      + "\t\t\"type\": \"event\"\n"
      + "\t},\n"
      + "\t\t{\n"
      + "\t\t\"anonymous\": false,\n"
      + "\t\t\"inputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"indexed\": true,\n"
      + "\t\t\t\t\"name\": \"from\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t},\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"indexed\": true,\n"
      + "\t\t\t\t\"name\": \"to\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t},\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"indexed\": false,\n"
      + "\t\t\t\t\"name\": \"value\",\n"
      + "\t\t\t\t\"type\": \"uint256\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"name\": \"Transfer\",\n"
      + "\t\t\"type\": \"event\"\n"
      + "\t},\n"
      + "\t{\n"
      + "\t\t\"anonymous\": false,\n"
      + "\t\t\"inputs\": [\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"indexed\": true,\n"
      + "\t\t\t\t\"name\": \"owner\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t},\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"indexed\": true,\n"
      + "\t\t\t\t\"name\": \"spender\",\n"
      + "\t\t\t\t\"type\": \"address\"\n"
      + "\t\t\t},\n"
      + "\t\t\t{\n"
      + "\t\t\t\t\"indexed\": false,\n"
      + "\t\t\t\t\"name\": \"value\",\n"
      + "\t\t\t\t\"type\": \"uint256\"\n"
      + "\t\t\t}\n"
      + "\t\t],\n"
      + "\t\t\"name\": \"Approval\",\n"
      + "\t\t\"type\": \"event\"\n"
      + "\t}\n"
      + "]";

}
