spring:
  jpa:
    database: postgresql
#    show-sql: true
    hibernate:
      ddl-auto: update
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc.lob.non_contextual_creation: true
  datasource:
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pwd
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

server:
  port: 4142

external:
  covalenthq:
    url: https://api.covalenthq.com/v1/
    key: ckey_91bf3242cc5042599af1094b965
  harvest:
    url: https://api-ui.harvest.finance/
    key: 41e90ced-d559-4433-b390-af424fdc76d6


task:
  pool:
    fixedRate: 3600000 # Each hour
    enable: false
  vault:
    fixedRate: 3600000 # Each hour
    enable: false
  uni-pair:
    fixedRate: 86400000 # Everyday
    enable: false
  transaction:
    max-thread-size: 30
    fixedRate: 86400000 # Everyday
    enable: false
